chore: update gh workflows and readme

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -38,6 +38,12 @@ jobs:
           else
             echo "base_path=/$REPO_NAME" >> $GITHUB_OUTPUT
           fi
+      - name: Check required env vars
+        run: |
+          if [[ -z "${{ vars.NEXT_PUBLIC_API_BASE_URL }}" ]]; then
+            echo "Missing GitHub Actions variable: NEXT_PUBLIC_API_BASE_URL"
+            exit 1
+          fi
 
       - name: Build static site
         env:
